

export const Day1 = [
  {
    title: "Check-in",
    company_name: "",
    // icon: starbucks,
    iconBg: "#383E56",
    date: "12:30 PM",
    points: [
      "Developing and maintaining web applications using React.js and other related technologies.",
      "Collaborating with cross-functional teams including designers, product managers, and other developers to create high-quality products.",
      "Implementing responsive design and ensuring cross-browser compatibility.",
      "Participating in code reviews and providing constructive feedback to other developers.",
    ],
  },
  {
    title: "Inaugration",
    company_name: "Sir M Visvesvarya Auditorium",
    // icon: tesla,
    iconBg: "#E6DEDD",
    date: "2:30 PM",
    points: [
      "Developing and maintaining web applications using React.js and other related technologies.",
      "Collaborating with cross-functional teams including designers, product managers, and other developers to create high-quality products.",
      "Implementing responsive design and ensuring cross-browser compatibility.",
      "Participating in code reviews and providing constructive feedback to other developers.",
    ],
  },
  {
    title: "Snacks",
    company_name: "",
    // icon: shopify,
    iconBg: "#383E56",
    date: "4:00 PM",
    points: [
      "Developing and maintaining web applications using React.js and other related technologies.",
      "Collaborating with cross-functional teams including designers, product managers, and other developers to create high-quality products.",
      "Implementing responsive design and ensuring cross-browser compatibility.",
      "Participating in code reviews and providing constructive feedback to other developers.",
    ],
  },
  {
    title: "Hack Begins",
    company_name: "CSE LABS",
    // icon: meta,
    iconBg: "#E6DEDD",
    date: "4:30 PM",
    points: [
      "Developing and maintaining web applications using React.js and other related technologies.",
      "Collaborating with cross-functional teams including designers, product managers, and other developers to create high-quality products.",
      "Implementing responsive design and ensuring cross-browser compatibility.",
      "Participating in code reviews and providing constructive feedback to other developers.",
    ],
  },
  {
    title: "Mentoring Session 1",
    company_name: "CSE LABS",
    // icon: shopify,
    iconBg: "#383E56",
    date: "7:00 - 9:00 PM",
    points: [
      "Developing and maintaining web applications using React.js and other related technologies.",
      "Collaborating with cross-functional teams including designers, product managers, and other developers to create high-quality products.",
      "Implementing responsive design and ensuring cross-browser compatibility.",
      "Participating in code reviews and providing constructive feedback to other developers.",
    ],
  },
  {
    title: "Dinner",
    company_name: "Annapoorna Mess",
    // icon: meta,
    iconBg: "#E6DEDD",
    date: "8:00 PM",
    points: [
      "Developing and maintaining web applications using React.js and other related technologies.",
      "Collaborating with cross-functional teams including designers, product managers, and other developers to create high-quality products.",
      "Implementing responsive design and ensuring cross-browser compatibility.",
      "Participating in code reviews and providing constructive feedback to other developers.",
    ],
  },
]

export const Day2 = [
  {
    title: "Midnight Surprise",
    company_name: "Surprise Surprise",
    // icon: shopify,
    iconBg: "#383E56",
    date: "12:00 AM",
    points: [
      "Developing and maintaining web applications using React.js and other related technologies.",
      "Collaborating with cross-functional teams including designers, product managers, and other developers to create high-quality products.",
      "Implementing responsive design and ensuring cross-browser compatibility.",
      "Participating in code reviews and providing constructive feedback to other developers.",
    ],
  },
  {
    title: "Breakfast",
    company_name: "Annapoorna Mess",
    // icon: meta,
    iconBg: "#E6DEDD",
    date: "8:00 AM",
    points: [
      "Developing and maintaining web applications using React.js and other related technologies.",
      "Collaborating with cross-functional teams including designers, product managers, and other developers to create high-quality products.",
      "Implementing responsive design and ensuring cross-browser compatibility.",
      "Participating in code reviews and providing constructive feedback to other developers.",
    ],
  },
  {
    title: "Lunch",
    company_name: "Annapoorna Mess",
    // icon: meta,
    iconBg: "#E6DEDD",
    date: "1:30 PM",
    points: [
      "Developing and maintaining web applications using React.js and other related technologies.",
      "Collaborating with cross-functional teams including designers, product managers, and other developers to create high-quality products.",
      "Implementing responsive design and ensuring cross-browser compatibility.",
      "Participating in code reviews and providing constructive feedback to other developers.",
    ],
  },
  {
    title: "Partner Session",
    company_name: "APJ Abdul Kalam Seminar Hall",
    // icon: shopify,
    iconBg: "#383E56",
    date: "3:00 PM",
    points: [
      "Developing and maintaining web applications using React.js and other related technologies.",
      "Collaborating with cross-functional teams including designers, product managers, and other developers to create high-quality products.",
      "Implementing responsive design and ensuring cross-browser compatibility.",
      "Participating in code reviews and providing constructive feedback to other developers.",
    ],
  },
  {
    title: "Snacks",
    company_name: "",
    // icon: meta,
    iconBg: "#E6DEDD",
    date: "4:00 - 4:30 PM",
    points: [
      "Developing and maintaining web applications using React.js and other related technologies.",
      "Collaborating with cross-functional teams including designers, product managers, and other developers to create high-quality products.",
      "Implementing responsive design and ensuring cross-browser compatibility.",
      "Participating in code reviews and providing constructive feedback to other developers.",
    ],
  },
  {
    title: "Mentoring Session 2",
    company_name: "CSE LABS",
    // icon: meta,
    iconBg: "#E6DEDD",
    date: "7:00 - 9:00 PM",
    points: [
      "Developing and maintaining web applications using React.js and other related technologies.",
      "Collaborating with cross-functional teams including designers, product managers, and other developers to create high-quality products.",
      "Implementing responsive design and ensuring cross-browser compatibility.",
      "Participating in code reviews and providing constructive feedback to other developers.",
    ],
  },
  {
    title: "Dinner",
    company_name: "Annapoorna Mess",
    // icon: meta,
    iconBg: "#E6DEDD",
    date: "8:00 PM",
    points: [
      "Developing and maintaining web applications using React.js and other related technologies.",
      "Collaborating with cross-functional teams including designers, product managers, and other developers to create high-quality products.",
      "Implementing responsive design and ensuring cross-browser compatibility.",
      "Participating in code reviews and providing constructive feedback to other developers.",
    ],
  },

]
export const Day3 = [
  {
    title: "Midnight Surprise",
    company_name: "Surprise Surprise",
    // icon: meta,
    iconBg: "#E6DEDD",
    date: "12:00 AM",
    points: [
      "Developing and maintaining web applications using React.js and other related technologies.",
      "Collaborating with cross-functional teams including designers, product managers, and other developers to create high-quality products.",
      "Implementing responsive design and ensuring cross-browser compatibility.",
      "Participating in code reviews and providing constructive feedback to other developers.",
    ],
  },
  {
    title: "Breakfast",
    company_name: "Annapoorna Mess",
    // icon: meta,
    iconBg: "#E6DEDD",
    date: "8:00 AM",
    points: [
      "Developing and maintaining web applications using React.js and other related technologies.",
      "Collaborating with cross-functional teams including designers, product managers, and other developers to create high-quality products.",
      "Implementing responsive design and ensuring cross-browser compatibility.",
      "Participating in code reviews and providing constructive feedback to other developers.",
    ],
  },
  {
    title: "Preliminary Evaluation Round",
    company_name: "CSE Labs",
    // icon: shopify,
    iconBg: "#383E56",
    date: "8:30 - 10:30 AM",
    points: [
      "Developing and maintaining web applications using React.js and other related technologies.",
      "Collaborating with cross-functional teams including designers, product managers, and other developers to create high-quality products.",
      "Implementing responsive design and ensuring cross-browser compatibility.",
      "Participating in code reviews and providing constructive feedback to other developers.",
    ],
  },
  {
    title: "Final Project Submission",
    company_name: "Devfolio",
    // icon: meta,
    iconBg: "#E6DEDD",
    date: "11:00 AM",
    points: [
      "Developing and maintaining web applications using React.js and other related technologies.",
      "Collaborating with cross-functional teams including designers, product managers, and other developers to create high-quality products.",
      "Implementing responsive design and ensuring cross-browser compatibility.",
      "Participating in code reviews and providing constructive feedback to other developers.",
    ],
  },
  {
    title: "Lunch",
    company_name: "Annapoorna Mess",
    // icon: shopify,
    iconBg: "#383E56",
    date: "12:00 PM",
    points: [
      "Developing and maintaining web applications using React.js and other related technologies.",
      "Collaborating with cross-functional teams including designers, product managers, and other developers to create high-quality products.",
      "Implementing responsive design and ensuring cross-browser compatibility.",
      "Participating in code reviews and providing constructive feedback to other developers.",
    ],
  },
  {
    title: "Announcement of top 10 teams",
    company_name: "",
    // icon: meta,
    iconBg: "#E6DEDD",
    date: "1:00 PM",
    points: [
      "Developing and maintaining web applications using React.js and other related technologies.",
      "Collaborating with cross-functional teams including designers, product managers, and other developers to create high-quality products.",
      "Implementing responsive design and ensuring cross-browser compatibility.",
      "Participating in code reviews and providing constructive feedback to other developers.",
    ],
  },
  {
    title: "Final Evaluation Round",
    company_name: "APJ Abdul Kalam Seminar Hall",
    // icon: meta,
    iconBg: "#E6DEDD",
    date: "1:30 PM",
    points: [
      "Developing and maintaining web applications using React.js and other related technologies.",
      "Collaborating with cross-functional teams including designers, product managers, and other developers to create high-quality products.",
      "Implementing responsive design and ensuring cross-browser compatibility.",
      "Participating in code reviews and providing constructive feedback to other developers.",
    ],
  },
  {
    title: "Vote of Thanks",
    company_name: "APJ Abdul Kalam Seminar Hall",
    // icon: meta,
    iconBg: "#E6DEDD",
    date: "4:30 PM",
    points: [
      "Developing and maintaining web applications using React.js and other related technologies.",
      "Collaborating with cross-functional teams including designers, product managers, and other developers to create high-quality products.",
      "Implementing responsive design and ensuring cross-browser compatibility.",
      "Participating in code reviews and providing constructive feedback to other developers.",
    ],
  },

]

